# Generated by tf-migrate 1.3.0

component "terraform_module" {
  source = "./terraform_modules"

  inputs = {
    "bucket_name" = var.bucket_name
    "environment" = var.environment
    "tags"        = var.tags
  }


  providers = {
    aws = provider.aws.this
  }
}


