# Generated by tf-migrate 1.3.0


# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate

store "varset" "tokens" {
  id       = "varset-xvfRyT1qNahGfpWm"
  category = "env"
}


deployment "cli-driven-test-workspace-1" {
  inputs = {
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
    tags = {
      Owner   = "terraform-test-lab"
      Project = "cli-driven-test-workspace-1"
    }
    bucket_name = "my-unique-bucket-name-12345-sujay-test-cli"
    environment = "dev"
  }
  import = true
}



