# Generated by tf-migrate 1.3.0


# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate

deployment "deployment-1" {
  inputs = {
    environment = "dev"
    tags = {
      Owner   = "terraform-test-lab"
      Project = "vcs-driven-test-workspace-1"
    }
    bucket_name = "my-unique-bucket-name-12345-sujay-test-vcs"
  }
  import = true
}



