# Generated by tf-migrate 1.3.0

output "bucket_name" {
  description = "Name of the created S3 bucket"
  value       = component.terraform_module.bucket_name
  type        = string
}

output "bucket_arn" {
  description = "ARN of the created S3 bucket"
  value       = component.terraform_module.bucket_arn
  type        = string
}

