# Generated by tf-migrate 1.3.0

required_providers {
  aws = {
    source  = "hashicorp/aws"
    version = "~> 5.7.0"
  }
}

provider "aws" "this" {
  config {
    region     = "ap-south-1"
    access_key = var.access_key
    secret_key = var.secret_key
    token      = var.session_token
  }
}

